### ISSUE TITLE
deno support?

### ISSUE THREAD

**Issue by andykais** [DetachHead/ts-helpers#97]
is it possible to use this module inside deno? Skypack imports dont seem to work
```ts
import * as helpers from 'https://cdn.skypack.dev/ts-helpers'
// helpers is empty
```
and importing the source from github isnt an option either because paths arent fully resolved
```ts
import {exactly} from 'https://raw.githubusercontent.com/DetachHead/ts-helpers/master/src/utilityFunctions/misc.ts'
// error: Import 'https://raw.githubusercontent.com/DetachHead/ts-helpers/master/src/utilityFunctions/Any' failed: 404 Not Found
```

**Comment by KotlinIsland** [comment]
Demo is based 100 so I intent to add full support. Im embarrassed that we don't have support already.

**Comment by KotlinIsland** [comment]
Have you tried esm.sh?

**Comment by andykais** [comment]
no good
```
> import * as ts_helpers from 'https://esm.sh/ts-helpers'
undefined
> ts_helpers
Module { default: null }
```

**Comment by DetachHead** [comment]
@andykais might be because there's no `index.ts` anymore. I removed it because of conflicting names between functions/types between files that was becoming too difficult to work around (eg. Both `Array` and `String` have a `Head` type). If you have a better solution in mind I'm all ears. Cus I don't like how it is now

This means you have to import from individual files directly, so your second example in the OP should work with esm.sh. Let me know if it doesn't

**Comment by DetachHead** [comment]
the npm package has built `.js` and `.d.ts` files in the `dist` directory, however with deno you should be able to just import from `src`, for example:
```ts
import {exactly} from 'http://esm.sh/@detachhead/ts-helpers/src/utilityFunctions/misc.ts'
```

**Comment by DetachHead** [comment]
i'm not sure then sorry. unfortunately i've experienced lots of issues running & debuging with deno on my machines which is why i've stuck with node. if you or anyone else figures out how to get it working i'd happily accept a PR.

it may be something that fixes itself with #76, who knows

**Comment by KotlinIsland** [comment]
https://github.com/alephjs/esm.sh/issues/189

**Comment by andykais** [comment]
It works! The following snippet seems to do error on everything I throw at it
```ts
import { exactly } from 'http://esm.sh/@detachhead/ts-helpers@9.0.0-9b4a478c3a63affa1f7f29aeabc2e5f76583ddfc/dist/utilityFunctions/misc'
import * as z from 'https://deno.land/x/zod@v3.9.0/mod.ts'


interface Foo {
  bar: string
  baz?: string // removing this line gives an error
  bot: 'a' | 'b'
}

const FooValidator = z.object({
  bar: z.string(),
  baz: z.string().optional(), // removing this line gives the error
  bot: z.union([z.literal('a'), z.literal('b')]), // adding/removing a literal from the union gives the error
})

exactly({} as z.input<typeof FooValidator>, {} as Foo)
```

> //values (also does a runtime assertion on the values)

Is this opt-out though? These are definitely not two runtime equivalent values


would you plan to publish to the deno repository (https://deno.land/x)?
